import Foundation

extension NSImage.Name
{
  static let prApproved = "prApproved"
  static let prClosed = "prClosed"
  static let prMerged = "prMerged"
  static let prNeedsWork = "prNeedsWork"
  static let xtActionButtonEmpty = "actionButtonEmpty"
  static let xtBitBucketTemplate = "bitbucketTemplate"
  static let xtBranchTemplate = "branchTemplate"
  static let xtBuildFailed = "buildFailed"
  static let xtBuildInProgress = "buildInProgress"
  static let xtBuildSucceeded = "buildSucceeded"
  static let xtNoBuilds = "noBuilds"
  static let xtCloudTemplate = "cloudTemplate"
  static let xtFileTemplate = "fileTemplate"
  static let xtFolderTemplate = "folderTemplate"
  static let xtGitHubTemplate = "githubTemplate"
  static let xtGitLabTemplate = "gitlabTemplate"
  static let xtRevertTemplate = "revertTemplate"
  static let xtStageAllTemplate = "stageAllTemplate"
  static let xtStageButtonHover = "stageButtonHover"
  static let xtStageButtonPressed = "stageButtonPressed"
  static let xtStagingTemplate = "stagingTemplate"
  static let xtStashTemplate = "stashTemplate"
  static let xtSubmoduleTemplate = "submoduleTemplate"
  static let xtTagTemplate = "tagTemplate"
  static let xtTeamCityTemplate = "teamcityTemplate"
  static let xtTracking = "trackingTemplate"
  static let xtTrackingMissing = "trackingMissing"
  static let xtUnstageAllTemplate = "unstageAllTemplate"
  static let xtUnstageButtonHover = "unstageButtonHover"
  static let xtUnstageButtonPressed = "unstageButtonPressed"
}
