import Foundation

/// Collects menu items into an array, for use with the `NSMenu(title:builder:)`
/// initializer.
@resultBuilder
struct MenuBuilder: ArrayBuilder
{
  typealias Element = NSMenuItem

  /// Converts a menu into an item with a submenu.
  static func buildExpression(_ menu: NSMenu) -> [NSMenuItem]
  {
    let item = NSMenuItem(title: menu.title, action: nil, keyEquivalent: "")

    item.submenu = menu
    return [item]
  }
}

extension NSMenu
{
  /// Constructs a menu from an array of items generated by a builder.
  convenience init(title: String = "",
                   @MenuBuilder _ builder: () -> [NSMenuItem])
  {
    self.init(title: title)

    setItems(builder: builder)
  }

  func setItems(@MenuBuilder builder: () -> [NSMenuItem])
  {
    items = builder()
  }

  func appendItems(@MenuBuilder builder: () -> [NSMenuItem])
  {
    items.append(contentsOf: builder())
  }
}
